/*
 * Boot-time check that the compiled model still matches the PC model.
 *
 * The vectors and expected probabilities are generated by
 * python/export/check_c_parity.py from real validation windows, so this
 * catches an exported table that has drifted out of step with the firmware —
 * a failure that would otherwise look like the model quietly getting worse on
 * device rather than anything breaking.
 */
#pragma once

#include "esp_err.h"
#include "esp_log.h"

#include "wisense_gbdt.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Score the baked-in vectors and compare against the PC results.
 *
 * @param tolerance Largest acceptable absolute probability difference.
 * @return ESP_OK when every stage of every vector matches.
 */
esp_err_t wisense_csi_selftest_run(float tolerance);

#ifdef __cplusplus
}
#endif
