/*
 * Generated by python/export/export_cascade_c.py — do not edit by hand.
 *
 * Source model : csi_cascade.joblib
 * Source config: preprocess_config.json
 * Stages       : occupied 200x5800n, motion 200x5800n, fall 150x3874n
 */
#pragma once

#include <stdint.h>

#include "wisense_gbdt.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Feature vector length shared by every stage (see extract_features()). */
#define WISENSE_CSI_FEATURE_DIM 75

/** Subcarriers per CSI packet after the HT40 mask and downsample. */
#define WISENSE_CSI_NUM_SC 32

/** Validation-tuned operating point for each stage. */
#define WISENSE_CSI_THRESHOLD_OCCUPIED 0.5f
#define WISENSE_CSI_THRESHOLD_MOTION   0.25f
#define WISENSE_CSI_THRESHOLD_FALL     0.5f

extern const wisense_gbdt_model_t wisense_csi_model_occupied;
extern const wisense_gbdt_model_t wisense_csi_model_motion;
extern const wisense_gbdt_model_t wisense_csi_model_fall;

/**
 * @brief Empty-room reference baseline the model was trained against.
 *
 * Subtracted from every packet's amplitude before features are built.  Live
 * calibration replaces this at runtime; it is the fallback when the room is
 * never observed empty.
 */
extern const float wisense_csi_reference_baseline[WISENSE_CSI_NUM_SC];

/** Complex tones in one HT40 CSI packet (384 bytes = 192 I/Q pairs). */
#define WISENSE_CSI_NUM_COMPLEX 192

/** Tones left after removing guard / null / DC bins. */
#define WISENSE_CSI_NUM_VALID_SC 166

/** Usable HT40 tones, ascending, as indices into the 192 complex tones. */
extern const uint8_t wisense_csi_valid_sc[WISENSE_CSI_NUM_VALID_SC];

/** Which of the valid tones survive the downsample to WISENSE_CSI_NUM_SC. */
extern const uint8_t wisense_csi_downsample_idx[WISENSE_CSI_NUM_SC];

#ifdef __cplusplus
}
#endif
