#!/usr/bin/env python3
"""Verify the exported C cascade reproduces scikit-learn, then emit a self-test.

Two independent checks, because a silent numerical divergence between the PC
model and the firmware would look exactly like "the model got worse on device":

1. Host check — re-flatten each stage with export_cascade_c.flatten_stage() and
   walk the node arrays using the C evaluator's exact semantics (float32
   threshold compares, double accumulation), then diff against
   predict_proba() over real validation windows.  This catches the parts most
   likely to be wrong: child indexing, split direction, baseline handling.

2. Device check — write wisense_csi_selftest.c holding real feature vectors and
   their expected probabilities.  The firmware runs it at boot, so the compiled
   Xtensa build is checked on the actual chip rather than assumed correct.
"""

import argparse
import sys
from pathlib import Path

import joblib
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from export_cascade_c import STAGES, flatten_stage, format_float


def evaluate_c_semantics(nodes, roots, baseline, features):
    """Walk the exported nodes exactly as wisense_gbdt_raw_score() does."""
    accumulator = float(baseline)
    for root in roots:
        node = nodes[root]
        while not node['is_leaf']:
            # float32 on both sides — the C code compares float32 feature values
            # against float32 thresholds, while sklearn uses float64 thresholds.
            value = np.float32(features[node['feature']])
            threshold = np.float32(node['value'])
            node = nodes[node['left']] if value <= threshold else nodes[node['right']]
        accumulator += float(np.float32(node['value']))
    return 1.0 / (1.0 + np.exp(-accumulator))


def emit_selftest(out_path, vectors, expected, packets, packet_amplitudes,
                  window, window_features):
    lines = [
        '/* Generated by python/export/check_c_parity.py — do not edit by hand. */',
        '#include "wisense_csi_selftest.h"',
        '',
        '#include "wisense_csi_features.h"',
        '#include "wisense_csi_model.h"',
        '',
        f'#define SELFTEST_VECTORS {len(vectors)}',
        f'#define SELFTEST_PACKETS {len(packets)}',
        f'#define SELFTEST_WINDOW_ROWS {len(window)}',
        '',
        '/* Raw gain-compensated CSI, exactly as the WiFi callback hands it over. */',
        f'static const int16_t s_raw_packets[SELFTEST_PACKETS][{len(packets[0])}] = {{',
    ]
    for packet in packets:
        lines.append('    {')
        for start in range(0, len(packet), 16):
            lines.append('        ' + ' '.join(f'{int(v)},' for v in packet[start:start + 16]))
        lines.append('    },')
    lines.append('};')
    lines.append('')
    lines.append('/* parse_csi_amplitude() output for each of those packets. */')
    lines.append('static const float s_packet_amplitude[SELFTEST_PACKETS][WISENSE_CSI_NUM_SC] = {')
    for row in packet_amplitudes:
        lines.append('    {')
        for start in range(0, len(row), 6):
            lines.append('        ' + ' '.join(f'{format_float(v)},' for v in row[start:start + 6]))
        lines.append('    },')
    lines.append('};')
    lines.append('')
    lines.append('/* A baseline-subtracted window and the 75 features it must produce. */')
    lines.append('static const float s_window[SELFTEST_WINDOW_ROWS][WISENSE_CSI_NUM_SC] = {')
    for row in window:
        lines.append('    {')
        for start in range(0, len(row), 6):
            lines.append('        ' + ' '.join(f'{format_float(v)},' for v in row[start:start + 6]))
        lines.append('    },')
    lines.append('};')
    lines.append('')
    lines.append('static const float s_window_features[WISENSE_CSI_FEATURE_DIM] = {')
    for start in range(0, len(window_features), 6):
        chunk = window_features[start:start + 6]
        lines.append('    ' + ' '.join(f'{format_float(v)},' for v in chunk))
    lines.append('};')
    lines.append('')
    lines.append('static const float s_features[SELFTEST_VECTORS][WISENSE_CSI_FEATURE_DIM] = {')
    for vector in vectors:
        lines.append('    {')
        for start in range(0, len(vector), 6):
            chunk = vector[start:start + 6]
            lines.append('        ' + ' '.join(f'{format_float(v)},' for v in chunk))
        lines.append('    },')
    lines.append('};')
    lines.append('')
    lines.append('/* occupied, motion, fall — as computed by scikit-learn on the PC. */')
    lines.append('static const float s_expected[SELFTEST_VECTORS][3] = {')
    for row in expected:
        lines.append('    { ' + ' '.join(f'{format_float(v)},' for v in row) + ' },')
    lines.append('};')
    lines.append('')
    lines.append(SELFTEST_BODY)
    out_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


SELFTEST_BODY = '''static const char *TAG = "csi_selftest";

static float absolute(float value)
{
    return (value < 0.0f) ? -value : value;
}

/**
 * Check the packet parser and the window feature builder.
 *
 * These run before the trees ever see anything, so an error here shifts every
 * feature at once — the trees would still evaluate perfectly against inputs
 * that no longer mean what they meant during training.
 */
static int selftest_features(float tolerance, float *worst)
{
    int failures = 0;
    float amplitude[WISENSE_CSI_NUM_SC];

    for (int p = 0; p < SELFTEST_PACKETS; p++) {
        if (!wisense_csi_packet_amplitude(s_raw_packets[p],
                                          sizeof(s_raw_packets[p]) / sizeof(int16_t),
                                          amplitude)) {
            ESP_LOGE(TAG, "packet %d rejected, but the PC pipeline accepted it", p);
            failures++;
            continue;
        }
        for (int sc = 0; sc < WISENSE_CSI_NUM_SC; sc++) {
            const float delta = absolute(amplitude[sc] - s_packet_amplitude[p][sc]);
            if (delta > *worst) {
                *worst = delta;
            }
            if (delta > tolerance) {
                ESP_LOGE(TAG, "packet %d sc %d: got %.4f expected %.4f",
                         p, sc, amplitude[sc], s_packet_amplitude[p][sc]);
                failures++;
            }
        }
    }

    float features[WISENSE_CSI_FEATURE_DIM];
    const wisense_csi_window_t window = {
        .storage = &s_window[0][0],
        .capacity = SELFTEST_WINDOW_ROWS,
        .start = 0,
        .count = SELFTEST_WINDOW_ROWS,
    };
    wisense_csi_window_features(&window, features);
    for (int f = 0; f < WISENSE_CSI_FEATURE_DIM; f++) {
        const float delta = absolute(features[f] - s_window_features[f]);
        if (delta > *worst) {
            *worst = delta;
        }
        if (delta > tolerance) {
            ESP_LOGE(TAG, "feature %d: got %.6f expected %.6f",
                     f, features[f], s_window_features[f]);
            failures++;
        }
    }

    /* The same window offset inside the ring must give identical features;
     * this is what catches a wrap-around indexing mistake. */
    const uint16_t offset = SELFTEST_WINDOW_ROWS / 2;
    float rotated_features[WISENSE_CSI_FEATURE_DIM];
    const wisense_csi_window_t rotated = {
        .storage = &s_window[0][0],
        .capacity = SELFTEST_WINDOW_ROWS,
        .start = offset,
        .count = SELFTEST_WINDOW_ROWS,
    };
    wisense_csi_window_features(&rotated, rotated_features);
    for (int f = 0; f < WISENSE_CSI_FEATURE_DIM; f++) {
        /* Order-independent statistics only: means, energies and standard
         * deviations must be unchanged by where the window starts. The two
         * delta features legitimately differ, since rotating changes which
         * rows are adjacent. */
        if (f >= WISENSE_CSI_NUM_SC * 2 + 3 && f < WISENSE_CSI_NUM_SC * 2 + 5) {
            continue;
        }
        if (absolute(rotated_features[f] - features[f]) > tolerance) {
            ESP_LOGE(TAG, "ring wrap changed feature %d: %.6f vs %.6f",
                     f, rotated_features[f], features[f]);
            failures++;
        }
    }

    return failures;
}

esp_err_t wisense_csi_selftest_run(float tolerance)
{
    const wisense_gbdt_model_t *stages[3] = {
        &wisense_csi_model_occupied,
        &wisense_csi_model_motion,
        &wisense_csi_model_fall,
    };
    static const char *names[3] = { "occupied", "motion", "fall" };

    float worst = 0.0f;
    int failures = selftest_features(tolerance, &worst);

    for (int v = 0; v < SELFTEST_VECTORS; v++) {
        for (int s = 0; s < 3; s++) {
            float got = wisense_gbdt_predict_proba(stages[s], s_features[v]);
            const float delta = absolute(got - s_expected[v][s]);
            if (delta > worst) {
                worst = delta;
            }
            if (delta > tolerance) {
                failures++;
                ESP_LOGE(TAG, "vector %d %s: got %.6f expected %.6f (delta %.6f)",
                         v, names[s], got, s_expected[v][s], delta);
            }
        }
    }

    if (failures) {
        ESP_LOGE(TAG, "FAIL - %d checks diverge from the PC pipeline", failures);
        return ESP_ERR_INVALID_STATE;
    }

    ESP_LOGI(TAG, "PASS - %d packets, %d-row window and %d model vectors match "
                  "the PC pipeline (worst delta %.2e)",
             SELFTEST_PACKETS, SELFTEST_WINDOW_ROWS, SELFTEST_VECTORS, worst);
    return ESP_OK;
}
'''


def build_feature_fixtures(capture_path, n_packets, n_window_rows):
    """Take real packets off a capture and record what Python makes of them.

    Uses the preprocessing functions directly rather than a reimplementation,
    so the expected values in the self-test are the training pipeline's own
    output, not a second opinion about what it should be.
    """
    import csv

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from preprocess.preprocess_csi import (EXPECTED_LEN, extract_features,
                                           parse_csi_amplitude, parse_csi_iq)

    raw_packets, amplitudes = [], []
    with Path(capture_path).open(newline='', encoding='utf-8', errors='replace') as handle:
        for row in csv.DictReader(handle):
            if len(raw_packets) >= n_packets and len(amplitudes) >= n_window_rows:
                break
            try:
                if int(row.get('len', 0)) != EXPECTED_LEN:
                    continue
            except (TypeError, ValueError):
                continue
            amplitude = parse_csi_amplitude(row['data'], expected_len=EXPECTED_LEN)
            if amplitude is None:
                continue
            if len(raw_packets) < n_packets:
                i_vals, q_vals = parse_csi_iq(row['data'], expected_len=EXPECTED_LEN)
                interleaved = np.empty(EXPECTED_LEN, dtype=np.int64)
                interleaved[0::2] = i_vals.astype(np.int64)
                interleaved[1::2] = q_vals.astype(np.int64)
                if np.any(np.abs(interleaved) > 32767):
                    continue
                raw_packets.append(interleaved)
            if len(amplitudes) < n_window_rows:
                amplitudes.append(amplitude)

    if len(raw_packets) < n_packets or len(amplitudes) < n_window_rows:
        raise SystemExit(f'{capture_path} did not yield enough usable packets')

    packet_amplitudes = [
        parse_csi_amplitude(
            '[' + ','.join(str(int(v)) for v in packet) + ']', expected_len=EXPECTED_LEN,
        )
        for packet in raw_packets
    ]

    # Subtract the median so the window looks like the baseline-corrected data
    # the feature builder actually receives at run time.
    window = np.asarray(amplitudes, dtype=np.float32)
    window = window - np.median(window, axis=0).astype(np.float32)
    return raw_packets, packet_amplitudes, window, extract_features(window)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--model', default='models/csi_cascade.joblib')
    parser.add_argument('--val', default='data/dataset/processed/val.npz')
    parser.add_argument('--samples', type=int, default=400,
                        help='Validation windows used for the host comparison')
    parser.add_argument('--selftest-vectors', type=int, default=8,
                        help='Vectors baked into the firmware self-test')
    parser.add_argument('--tolerance', type=float, default=1e-4,
                        help='Maximum acceptable probability difference')
    parser.add_argument('--out-dir', default='firmware/components/wisense_csi_infer')
    parser.add_argument('--capture',
                        default='data/dataset/empty_fan_on/s001_empty.csv',
                        help='Capture CSV supplying real packets for the feature self-test. '
                             'Must be a raw capture with a "data" column, not a session manifest.')
    parser.add_argument('--packet-vectors', type=int, default=4)
    parser.add_argument('--window-rows', type=int, default=24)
    args = parser.parse_args()

    bundle = joblib.load(args.model)
    with np.load(args.val) as data:
        features_all = data['X_feat'].astype(np.float32)
        class_id = data['class_id'].astype(np.int8)

    rng = np.random.default_rng(0)
    pick = rng.choice(len(features_all), size=min(args.samples, len(features_all)),
                      replace=False)
    features = features_all[pick]

    print(f'Comparing {len(features)} validation windows across '
          f'{len(STAGES)} stages\n')

    worst_overall = 0.0
    sklearn_probs = {}
    for stage in STAGES:
        model = bundle['models'][stage]
        nodes, roots, baseline = flatten_stage(model)
        reference = model.predict_proba(features)[:, 1]
        exported = np.asarray([
            evaluate_c_semantics(nodes, roots, baseline, row) for row in features
        ])
        sklearn_probs[stage] = reference
        delta = np.abs(exported - reference)
        threshold = bundle['thresholds'][stage]
        flips = int(np.sum((exported >= threshold) != (reference >= threshold)))
        worst_overall = max(worst_overall, float(delta.max()))
        status = 'OK ' if delta.max() <= args.tolerance and flips == 0 else 'FAIL'
        print(f'  [{status}] {stage:9} max|delta|={delta.max():.3e} '
              f'mean={delta.mean():.3e} decision flips at thr={threshold}: {flips}')

    print(f'\nWorst probability difference overall: {worst_overall:.3e}')
    if worst_overall > args.tolerance:
        print('FAILED — the exported trees do not reproduce scikit-learn.')
        return 1

    # Bias the self-test toward class variety so a broken export cannot pass by
    # only ever hitting the same region of the trees.
    chosen = []
    for target in (0, 1, 2, 3):
        matches = np.flatnonzero(class_id[pick] == target)
        chosen.extend(pick[matches[:2]].tolist())
    chosen = (chosen + pick.tolist())[:args.selftest_vectors]

    vectors = features_all[chosen]
    expected = np.stack([
        bundle['models'][stage].predict_proba(vectors)[:, 1] for stage in STAGES
    ], axis=1)

    packets, packet_amplitudes, window, window_features = build_feature_fixtures(
        args.capture, args.packet_vectors, args.window_rows,
    )

    out_path = Path(args.out_dir) / 'wisense_csi_selftest.c'
    emit_selftest(out_path, vectors, expected, packets, packet_amplitudes,
                  window, window_features)
    print(f'Wrote device self-test: {out_path}')
    print(f'  {len(vectors)} model vectors, {len(packets)} raw packets, '
          f'{len(window)}-row feature window')
    print('PASSED')
    return 0


if __name__ == '__main__':
    sys.exit(main())
