#!/usr/bin/env python3
"""Compile the trained sklearn CSI cascade into flat C arrays for the ESP32-S3.

The cascade is three HistGradientBoostingClassifier ensembles, not a neural
network, so there is no TFLite operator to target.  A gradient-boosted tree is
already a lookup structure, though: exporting the split nodes directly gives
bit-comparable inference with no interpreter, no quantisation error and no heap.

Each stage becomes one node array with every tree concatenated, plus a table of
per-tree root indices.  ``value`` doubles as the split threshold on internal
nodes and the leaf output on leaves, which keeps the struct at 12 bytes.

Also emits the empty-room reference baseline from preprocess_config.json, so
the firmware defaults to the same baseline the model was trained against.
"""

import argparse
import json
import sys
from pathlib import Path

import joblib
import numpy as np

STAGES = ('occupied', 'motion', 'fall')

HEADER_TEMPLATE = '''/*
 * Generated by python/export/export_cascade_c.py — do not edit by hand.
 *
 * Source model : {model_name}
 * Source config: {config_name}
 * Stages       : {stage_summary}
 */
#pragma once

#include <stdint.h>

#include "wisense_gbdt.h"

#ifdef __cplusplus
extern "C" {{
#endif

/** Feature vector length shared by every stage (see extract_features()). */
#define WISENSE_CSI_FEATURE_DIM {feature_dim}

/** Subcarriers per CSI packet after the HT40 mask and downsample. */
#define WISENSE_CSI_NUM_SC {num_sc}

/** Validation-tuned operating point for each stage. */
#define WISENSE_CSI_THRESHOLD_OCCUPIED {thr_occupied}f
#define WISENSE_CSI_THRESHOLD_MOTION   {thr_motion}f
#define WISENSE_CSI_THRESHOLD_FALL     {thr_fall}f

extern const wisense_gbdt_model_t wisense_csi_model_occupied;
extern const wisense_gbdt_model_t wisense_csi_model_motion;
extern const wisense_gbdt_model_t wisense_csi_model_fall;

/**
 * @brief Empty-room reference baseline the model was trained against.
 *
 * Subtracted from every packet's amplitude before features are built.  Live
 * calibration replaces this at runtime; it is the fallback when the room is
 * never observed empty.
 */
extern const float wisense_csi_reference_baseline[WISENSE_CSI_NUM_SC];

/** Complex tones in one HT40 CSI packet (384 bytes = 192 I/Q pairs). */
#define WISENSE_CSI_NUM_COMPLEX {num_complex}

/** Tones left after removing guard / null / DC bins. */
#define WISENSE_CSI_NUM_VALID_SC {num_valid_sc}

/** Usable HT40 tones, ascending, as indices into the {num_complex} complex tones. */
extern const uint8_t wisense_csi_valid_sc[WISENSE_CSI_NUM_VALID_SC];

/** Which of the valid tones survive the downsample to WISENSE_CSI_NUM_SC. */
extern const uint8_t wisense_csi_downsample_idx[WISENSE_CSI_NUM_SC];

#ifdef __cplusplus
}}
#endif
'''


def flatten_stage(model):
    """Concatenate every tree of one stage into a single node array.

    Child indices are absolute into the concatenated array, so evaluation never
    needs the per-tree offset — only the root does.
    """
    nodes, roots = [], []
    for predictor, in model._predictors:
        raw = predictor.nodes
        if raw['is_categorical'].any():
            raise ValueError('categorical splits are not supported by the C evaluator')
        base = len(nodes)
        roots.append(base)
        for node in raw:
            is_leaf = bool(node['is_leaf'])
            nodes.append({
                # A leaf stores its output here; a split stores its threshold.
                'value': float(node['value'] if is_leaf else node['num_threshold']),
                'left': base + int(node['left']),
                'right': base + int(node['right']),
                'feature': 0 if is_leaf else int(node['feature_idx']),
                'is_leaf': int(is_leaf),
            })
    if len(nodes) > 0xFFFF:
        raise ValueError(f'{len(nodes)} nodes exceeds the uint16 child index range')
    baseline = float(np.ravel(model._baseline_prediction)[0])
    return nodes, roots, baseline


def format_float(value):
    """Emit a float32 literal that round-trips exactly."""
    return f'{np.float32(value)!r}f'.replace('np.float32(', '').replace(')f', 'f')


def emit_stage(out, stage, nodes, roots, baseline):
    out.append(f'/* ---- {stage}: {len(roots)} trees, {len(nodes)} nodes ---- */')
    out.append(f'static const wisense_gbdt_node_t s_{stage}_nodes[{len(nodes)}] = {{')
    for node in nodes:
        out.append(
            f"    {{ {format_float(node['value']):>16}, {node['left']:5d}, "
            f"{node['right']:5d}, {node['feature']:3d}, {node['is_leaf']} }},"
        )
    out.append('};')
    out.append('')
    out.append(f'static const uint16_t s_{stage}_roots[{len(roots)}] = {{')
    for chunk_start in range(0, len(roots), 12):
        chunk = roots[chunk_start:chunk_start + 12]
        out.append('    ' + ' '.join(f'{value},' for value in chunk))
    out.append('};')
    out.append('')
    out.append(f'const wisense_gbdt_model_t wisense_csi_model_{stage} = {{')
    out.append(f'    .nodes = s_{stage}_nodes,')
    out.append(f'    .tree_root = s_{stage}_roots,')
    out.append(f'    .n_trees = {len(roots)},')
    out.append(f'    .baseline = {format_float(baseline)},')
    out.append('};')
    out.append('')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--model', default='models/csi_cascade.joblib')
    parser.add_argument('--config', default='data/dataset/processed/preprocess_config.json')
    parser.add_argument(
        '--out-dir',
        default='firmware/components/wisense_csi_infer',
        help='Component directory receiving wisense_csi_model.{c,h}',
    )
    args = parser.parse_args()

    bundle = joblib.load(args.model)
    config = json.loads(Path(args.config).read_text(encoding='utf-8'))
    if bundle['feature_dim'] != config['feature_dim']:
        raise SystemExit('model and preprocessing config disagree on feature_dim')

    out_dir = Path(args.out_dir)
    (out_dir / 'include').mkdir(parents=True, exist_ok=True)

    body, summary, total_nodes = [], [], 0
    for stage in STAGES:
        nodes, roots, baseline = flatten_stage(bundle['models'][stage])
        emit_stage(body, stage, nodes, roots, baseline)
        summary.append(f'{stage} {len(roots)}x{len(nodes)}n')
        total_nodes += len(nodes)

    baseline_ref = np.asarray(config['reference_baseline'], dtype=np.float32)
    num_sc = int(config['num_subcarriers'])
    num_complex = int(config['expected_len']) // 2
    guard_sc = {int(value) for value in config['ht40_guard_sc']}
    # Rebuilt exactly as preprocess_csi.py does, so the C path indexes the same
    # tones in the same order rather than re-deriving them from a mask.
    valid_sc = np.asarray(
        [i for i in range(num_complex) if i not in guard_sc], dtype=np.int32,
    )
    downsample_idx = np.linspace(0, len(valid_sc) - 1, num=num_sc, dtype=np.int32)
    if len(valid_sc) != int(config['ht40_valid_sc_count']):
        raise SystemExit('rebuilt valid-subcarrier list disagrees with the config count')
    if not np.array_equal(valid_sc[downsample_idx],
                          np.asarray(config['ht40_selected_sc'], dtype=np.int32)):
        raise SystemExit('rebuilt downsample indices disagree with ht40_selected_sc')
    if baseline_ref.shape != (num_sc,):
        raise SystemExit('config baseline does not match num_subcarriers')

    body.append(f'const float wisense_csi_reference_baseline[{num_sc}] = {{')
    for chunk_start in range(0, num_sc, 6):
        chunk = baseline_ref[chunk_start:chunk_start + 6]
        body.append('    ' + ' '.join(f'{format_float(v)},' for v in chunk))
    body.append('};')
    body.append('')
    body.append(f'const uint8_t wisense_csi_valid_sc[{len(valid_sc)}] = {{')
    for chunk_start in range(0, len(valid_sc), 16):
        chunk = valid_sc[chunk_start:chunk_start + 16]
        body.append('    ' + ' '.join(f'{int(v)},' for v in chunk))
    body.append('};')
    body.append('')
    body.append(f'const uint8_t wisense_csi_downsample_idx[{num_sc}] = {{')
    for chunk_start in range(0, num_sc, 12):
        chunk = downsample_idx[chunk_start:chunk_start + 12]
        body.append('    ' + ' '.join(f'{int(v)},' for v in chunk))
    body.append('};')

    header = HEADER_TEMPLATE.format(
        model_name=Path(args.model).name,
        config_name=Path(args.config).name,
        stage_summary=', '.join(summary),
        feature_dim=bundle['feature_dim'],
        num_sc=num_sc,
        num_complex=num_complex,
        num_valid_sc=len(valid_sc),
        thr_occupied=bundle['thresholds']['occupied'],
        thr_motion=bundle['thresholds']['motion'],
        thr_fall=bundle['thresholds']['fall'],
    )
    source = (
        '/* Generated by python/export/export_cascade_c.py — do not edit by hand. */\n'
        '#include "wisense_csi_model.h"\n\n'
        + '\n'.join(body)
        + '\n'
    )

    header_path = out_dir / 'include' / 'wisense_csi_model.h'
    source_path = out_dir / 'wisense_csi_model.c'
    header_path.write_text(header, encoding='utf-8')
    source_path.write_text(source, encoding='utf-8')

    print(f'Stages     : {", ".join(summary)}')
    print(f'Total nodes: {total_nodes} (~{total_nodes * 12 / 1024:.0f} KB of .rodata)')
    print(f'Wrote      : {header_path}')
    print(f'Wrote      : {source_path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
